In [4]:
#1 layer Multilayer Perceptron
#Reference:
#https://databoys.github.io/Feedforward/
#https://www.doc.ic.ac.uk/~sgc/teaching/pre2012/v231/lecture13.html
#Search keywords: (Google)
#numerical calculation + multu layer perceptron

In [5]:
import scipy as sc
import numpy as np

In [6]:
# Input to NN
X = np.array([10, 30, 20])

In [7]:
#Weights - Input to Hidden Layer
W1 = np.array([[0.2, -0.1, 0.4],[0.7, -1.2, 1.2]])

In [8]:
#Weights - From Hidden to Output Layer
W2 = np.array([[1.1, 0.1],[3.1, 1.17]])

In [9]:
#Transpose is used for "Intermediate Output; Before Sigmoid Transformation"
W2T = W2.T

In [10]:
#Bias 
#CHNAGE: BIAS IS NOT USED; FIND OUT HOW IT CAN BE USED.
B = np.array([1, 1])

In [15]:
#Input to Hidden Layer
H_Mat = X.dot(W1.T)

In [16]:
#Sigmoid Transformation
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

In [17]:
#Sigmoid Transformation
H_Out = sigmoid(H_Mat)

In [18]:
# Intermediate Output; before final Sigmoid transformation
O = H_Out.dot(W2T)

In [19]:
#Final Output 
#Feedforward Output is "OF" Variable
OF = sigmoid(O)
OF

array([ 0.75019773,  0.95709878])

In [20]:
#CHANGE : The Hard Coded Dimensions.
def error_term(A, T):
    '''
    Function to calculate the error.
    Input:
    A -> Actual
    T -> Target
    Output:
    Outputs e
    '''
    one = np.ones((2,1))
    A1 = A.reshape(2,1)
    DI = one - A1
    T_MAT = np.diag(DI[:, 0])
    OF_new = A.dot(T_MAT)
    T_DIFF_OF = T-A
    T_DIFF_OF_NP_DIAG = np.diag(T_DIFF_OF)
    return(OF_new.dot(T_DIFF_OF_NP_DIAG))

In [21]:
#CHANGE : TARGET VALUES
T = np.array([1, 0]) 

In [22]:
E  = error_term(OF,T)

In [23]:
def error_hidden_layer(H, W, E):
    '''
    Function Determines Error of Hidden Layer.
    H -> Outputs of Hidden Layer
    W -> Weights from Hidden to Output Layer.
    E -> Error of Output Layer( Output of error_term function)
    '''
    #Below line will help to find ERROR of Hidden Layer `
    E_H_LAYER1 = E.dot(W)
    
    #CHANGE: Change the dimension and make it generic
    one = np.ones((2,1))
    
    #CHANGE: Change the dimension and make it generic
    ONE_MINUS_H_OUT = one - H.reshape(2,1)
    
    np.diag(ONE_MINUS_H_OUT[:, 0])
    
    #Error of Hidden Layer1
    Err_H = E_H_LAYER1.dot(np.diag(H)).dot(np.diag(ONE_MINUS_H_OUT[:,0]))
    
    return Err_H

In [24]:
Err_H = error_hidden_layer(H_Out, W2, E)

In [25]:
# CHANGE "N -> Learning Rate (EETA)" need to be dynamic.
def weight_update(Err_H, X, W1, N=0.1):
    '''
    Function updates weight as part of Backpropagation
    N -> Learning Rate (EETA)
    Err_H -> Error of Hidden Layer (Output of function error_hidden_layer)
    X -> Input to NN
    W1 -> Weights - input to hidden layer
    '''
    X_shape = X.shape[0]
    Err_H_shape = Err_H.shape[0]
    W1_new = (Err_H.reshape(Err_H_shape, 1).dot(X.reshape(1, X_shape)) * N) + W1
    return W1_new

In [26]:
W1_new = weight_update(Err_H, X, W1)

In [27]:
W1_new

array([[ 0.19993598, -0.10019206,  0.39987196],
       [ 0.69972544, -1.20082367,  1.19945089]])

In [28]:
W1

array([[ 0.2, -0.1,  0.4],
       [ 0.7, -1.2,  1.2]])

In [29]:
E

array([ 0.04681322, -0.03929915])

In [30]:
H_Out

array([ 0.99908895,  0.00669285])

In [31]:
W2_new = weight_update(E, H_Out, W2)

In [32]:
W2_new

array([[ 1.10467706,  0.10003133],
       [ 3.09607367,  1.1699737 ]])

In [33]:
W2

array([[ 1.1 ,  0.1 ],
       [ 3.1 ,  1.17]])

In [35]:
H_Out.shape[0]

2